### ISSUE TITLE
direction寻找线路有类似的API函数么?

### ISSUE THREAD

**Issue by Lchiffon** [badbye/baidumap#1]
网页在这里!

http://developer.baidu.com/map/index.php?title=webapi/direction-api

快点更新!

**Comment by badbye** [comment]
返回的值太多，不好处理啊．想要什么结果？

**Comment by Lchiffon** [comment]
其实有价值的也只是经纬度信息了

发自我的 iPad

**Comment by badbye** [comment]
done.
https://github.com/badbye/baidumap/blob/master/R/getRoute.R
