### ISSUE TITLE
Issue of getForm

### ISSUE THREAD

**Issue by Lchiffon** [badbye/baidumap#2]
> df = getRoute(origin = '北京大学', destination = '天安门',region = "北京")
> Error in getRouteXML(...) : could not find function "getForm"
> 
> df = getRoute('首都国际机场', '北京南苑机场')
> Error in getRouteXML(...) : could not find function "getForm"

getRoute.R:

rawData = getForm(serverAddress, mode = mode, ....)

**Comment by badbye** [comment]
Done. Forgot to import `getForm` from `Rcurl`.
BTW, `getForm` is a better function to send parameters when using API.

It works in RGui, If you are using Rstudio, you may get this error:

```
In addition: Warning message:
In fetch(key) : internal error -3 in R_decompress1
```

Currently I don't  know why.
