### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by polarlightman** [badbye/baidumap#3]
> install_github('badbye/baidumap')
> Downloading GitHub repo badbye/baidumap@master
> from URL https://api.github.com/repos/badbye/baidumap/zipball/master
> Installing baidumap
> "G:/RR/R-3.3.1/bin/x64/R" --no-site-file  \
>   --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/Administrator/AppData/Local/Temp/RtmpKKVfrt/devtools102012e914fd/badbye-baidumap-e078ef8"  \
>   --library="G:/RR/R-3.3.1/library"  \
>   --install-tests 
- installing _source_ package 'baidumap' ...
  *\* R
  *\* preparing package for lazy loading
  Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'bitops'
  ERROR: lazy loading failed for package 'baidumap'
- removing 'G:/RR/R-3.3.1/library/baidumap'
  Error: Command failed (1)

How to solve this problem ? Thankyou~

**Comment by badbye** [comment]
Install `bitops` and try again?
