### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by cyriltian** [badbye/baidumap#5]
Hi there, I got an issue when installing this package
I used the command `install_github('badbye/baidumap')`
however it didnt work
here is the info

>Downloading GitHub repo badbye/baidumap@master
from URL https://api.github.com/repos/badbye/baidumap/zipball/master
Installing baidumap
> "D:/R/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/xxx/AppData/Local/Temp/RtmpEjKydT/devtools28ac64c06807/badbye-baidumap-2779592"  \
  --library="D:/R/R-3.3.1/library" --install-tests 
>*installing *source* package 'baidumap' ...
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'bitops'
ERROR: lazy loading failed for package 'baidumap'
>*removing 'D:/R/R-3.3.1/library/baidumap'
Error: Command failed (1)

**Comment by badbye** [comment]
> there is no package called 'bitops'

Install `bitops` first?

**Comment by cyriltian** [comment]
> Install bitops first?

yep i tried but after that more and more packages are missing like jpeg, proto, mapproj...
it seems like endless for me...
thx all the same

**Comment by cyriltian** [comment]
tried four or five more packages
finally succeed
thx!
